GET http://localhost:3000
###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/1

###
PUT http://localhost:3000/users/1

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "dateJoined": "2024-07-28"

}

###
